holyketzer-moex_goalgo-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "custom_indexes#index"

  # Defines the routes for the CustomIndex resource
  resources :custom_indexes, except: [:edit, :update] do
    post :filter_check, on: :collection
  end
end

holyketzer-moex_goalgo-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Build your index</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-- Select2 Styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Select2 Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- Charts -->
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js" charset="utf-8"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Your Stock Index</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <% if current_user %>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<%= new_custom_index_path %>">Собрать новый индекс</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= custom_indexes_path %>">Мои индексы</a>
              </li>
            <% end %>
          </ul>
          <% if current_user %>
            <form action="<%= destroy_user_session_path %>" method="delete">
              <div class="btn btn-navbar btn-secondary btn-profile"><%= current_user.email %></div>
              <button class="btn btn-navbar btn-success" type="submit">Выйти</button>
            </form>
          <% else %>
            <form class="d-flex">
              <a class="btn btn-navbar btn-success" type="submit" href="<%= new_user_session_path %>">Войти</a>
              <a class="btn btn-navbar btn-primary" type="submit" href="<%= new_user_registration_path %>">Зарегистрироваться</a>
            </form>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if notice %>
            <div class="alert alert-warning" role="alert">
              <%= notice %>
            </div>
          <% end %>
          <% if alert %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
            </div>
          <% end %>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>